SELECT DEPARTMENT_NAME,locations.LOCATION_ID,STREET_ADDRESS,CITY,STATE_PROVINCE,COUNTRY_NAME
 FROM (locations
 INNER JOIN departments
 ON departments.LOCATION_ID=locations.LOCATION_ID) LEFT OUTER JOIN countries ON locations.COUNTRY_ID = countries.COUNTRY_ID;
SELECT concat(FIRST_NAME, ', ',LAST_NAME) as EMPLOYEE_NAME, departments.DEPARTMENT_ID, DEPARTMENT_NAME
 FROM employees
 LEFT OUTER JOIN departments 
ON departments.DEPARTMENT_ID=employees.DEPARTMENT_ID;
SELECT concat(FIRST_NAME, ', ',LAST_NAME) as EMPLOYEE_NAME, JOB_TITLE, departments.DEPARTMENT_ID, DEPARTMENT_NAME 
FROM ((employees 
LEFT OUTER JOIN departments
 ON departments.DEPARTMENT_ID=employees.DEPARTMENT_ID)
 LEFT OUTER JOIN jobs
 ON jobs.JOB_ID=employees.JOB_ID) LEFT OUTER JOIN locations ON locations.LOCATION_ID=departments.LOCATION_ID
 WHERE CITY='London';
SELECT DEPARTMENT_NAME, COUNT(*)
 FROM employees
 INNER JOIN departments 
ON employees.DEPARTMENT_ID=departments.DEPARTMENT_ID
 GROUP BY DEPARTMENT_NAME;
SELECT concat(FIRST_NAME,', ',LAST_NAME) as EMPLOYEE_NAME,HIRE_DATE
 FROM employees
 WHERE HIRE_DATE>(SELECT HIRE_DATE
 FROM employees
 WHERE LAST_NAME='Jones')
 ORDER BY HIRE_DATE;