SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) as EMPLOYEE_NAME,SALARY
 FROM employees
 WHERE SALARY>(SELECT SALARY FROM employees WHERE LAST_NAME='bull');
SELECT CONCAT(FIRST_NAME,', ',LAST_NAME) as EMPLOYEE_NAME,departments.DEPARTMENT_NAME
FROM employees
 LEFT OUTER JOIN departments 
ON departments.DEPARTMENT_ID=employees.DEPARTMENT_ID
 WHERE DEPARTMENT_NAME = 'IT';
SELECT CONCAT(FIRST_NAME,', ',LAST_NAME) as EMPLOYEE_NAME,jobs.JOB_TITLE 
FROM employees 
LEFT OUTER JOIN jobs
 ON jobs.JOB_ID=employees.JOB_ID
WHERE JOB_TITLE like '%Manager%';
SELECT CONCAT(FIRST_NAME,', ',LAST_NAME) as EMPLOYEE_NAME,SALARY
 FROM employees 
WHERE SALARY>(SELECT AVG(SALARY)
 FROM employees);
SELECT CONCAT(FIRST_NAME,', ',LAST_NAME) as EMPLOYEE_NAME,SALARY,jobs.JOB_TITLE,jobs.MIN_SALARY
FROM employees
 INNER JOIN jobs 
ON jobs.JOB_ID=employees.JOB_ID
 WHERE SALARY=MIN_SALARY;
SELECT CONCAT(FIRST_NAME,', ',LAST_NAME) as EMPLOYEE_NAME,SALARY 
FROM employees
 WHERE SALARY in (SELECT MIN(SALARY)
 FROM employees INNER JOIN departments ON departments.DEPARTMENT_ID=employees.DEPARTMENT_ID GROUP BY DEPARTMENT_NAME);
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,DEPARTMENT_NAME
 FROM employees 
LEFT OUTER JOIN departments 
ON departments.DEPARTMENT_ID=employees.DEPARTMENT_ID;
SELECT * 
FROM employees 
ORDER BY EMPLOYEE_ID DESC
LIMIT 10;